package main

import (
	"fmt"
	"os"

	"dbca_tui/internal/generator"
	"dbca_tui/internal/steps"
	"dbca_tui/internal/wizard"

	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	// Create all wizard steps
	wizardSteps := []wizard.Step{
		steps.NewOperationStep(),       // Step 1: Create or Delete database
		steps.NewCreationModeStep(),    // Step 2: Typical vs Advanced (Create only)
		steps.NewDeploymentStep(),      // Step 3: Single/RAC/RAC One Node (Create only)
		steps.NewTemplateStep(),        // Step 4: Template selection (Create only)
		steps.NewIdentificationStep(),  // Step 5: DB name, SID, CDB/PDB (Create only)
		steps.NewStorageStep(),         // Step 6: Storage configuration (Create only)
		steps.NewRecoveryStep(),        // Step 7: FRA & Archive Log (Create only)
		steps.NewNetworkStep(),         // Step 8: Listener (Create/Advanced only)
		steps.NewDataVaultStep(),       // Step 9: Data Vault (Create/Advanced only)
		steps.NewConfigStep(),          // Step 10: Memory, charset, etc. (Create only)
		steps.NewManagementStep(),      // Step 11: EM config (Create/Advanced only)
		steps.NewCredentialsStep(),     // Step 12: Passwords (Create only)
		steps.NewDeleteStep(),          // Step 13: Delete configuration (Delete only)
		steps.NewSummaryStep(),         // Step 14: Summary & command generation
	}

	// Create the wizard
	w := wizard.NewWizard(wizardSteps)

	// Create the bubbletea program
	p := tea.NewProgram(w, tea.WithAltScreen())

	// Run the program
	model, err := p.Run()
	if err != nil {
		fmt.Printf("Error running program: %v\n", err)
		os.Exit(1)
	}

	// Check if we should print the command
	if wiz, ok := model.(*wizard.Wizard); ok {
		if wiz.ShouldPrintCommand() {
			config := wiz.GetConfig()
			fmt.Println()
			if config.Operation == "delete" {
				fmt.Println("# DBCA Silent Mode Command - Delete Database")
			} else {
				fmt.Println("# DBCA Silent Mode Command - Create Database")
			}
			fmt.Println("# Generated by DBCA TUI")
			fmt.Println()
			fmt.Println(generator.GenerateCommandWithPasswords(config))
			fmt.Println()
		}
	}
}
