package main

import (
	"fmt"
	"os"

	"dbca_tui/internal/generator"
	"dbca_tui/internal/steps"
	"dbca_tui/internal/wizard"

	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	// Create all wizard steps
	wizardSteps := []wizard.Step{
		steps.NewCreationModeStep(),    // Step 1: Typical vs Advanced
		steps.NewDeploymentStep(),      // Step 2: Single/RAC/RAC One Node
		steps.NewTemplateStep(),        // Step 3: Template selection
		steps.NewIdentificationStep(),  // Step 4: DB name, SID, CDB/PDB
		steps.NewStorageStep(),         // Step 5: Storage configuration
		steps.NewRecoveryStep(),        // Step 6: FRA configuration
		steps.NewNetworkStep(),         // Step 7: Listener (Advanced only)
		steps.NewDataVaultStep(),       // Step 8: Data Vault (Advanced only)
		steps.NewConfigStep(),          // Step 9: Memory, charset, etc.
		steps.NewManagementStep(),      // Step 10: EM config (Advanced only)
		steps.NewCredentialsStep(),     // Step 11: Passwords
		steps.NewSummaryStep(),         // Step 12: Summary & command generation
	}

	// Create the wizard
	w := wizard.NewWizard(wizardSteps)

	// Create the bubbletea program
	p := tea.NewProgram(w, tea.WithAltScreen())

	// Run the program
	model, err := p.Run()
	if err != nil {
		fmt.Printf("Error running program: %v\n", err)
		os.Exit(1)
	}

	// Check if we should print the command
	if wiz, ok := model.(*wizard.Wizard); ok {
		if wiz.ShouldPrintCommand() {
			config := wiz.GetConfig()
			fmt.Println()
			fmt.Println("# DBCA Silent Mode Command")
			fmt.Println("# Generated by DBCA TUI")
			fmt.Println()
			fmt.Println(generator.GenerateCommandWithPasswords(config))
			fmt.Println()
		}
	}
}
